export { install } from "./scripts/install.js"
export { postBuild } from "./scripts/postbuild.js"
export { uninstall } from "./scripts/uninstall.js"
export { update } from "./scripts/update.js"
export { zip } from "./scripts/zip.js"
export * from "./utils/logger.js"
