export { configureDappConf } from "./scripts/dapp-conf.js"
export { install } from "./scripts/install.js"
export { uninstall } from "./scripts/uninstall.js"
export { update } from "./scripts/update.js"
export { zip } from "./scripts/zip.js"
export { isReactProject } from "./utils/is-react-project.js"
