name: CI

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8.15.6

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Create data directory
        run: mkdir -p ~/minimadocker9001

      - name: Run Minima container
        run: |
          docker run -d \
            -e minima_mdspassword=test \
            -e minima_desktop=true \
            -e minima_rpcenable=true \
            -e minima_rpcssl=true \
            -e minima_host=127.0.0.1 \
            -v ~/minimadocker9001:/home/minima/data \
            -p 9001-9005:9001-9005 \
            --name minima9001 \
            minimaglobal/minima:latest

      - name: Wait for Minima and verify it's running
        timeout-minutes: 2
        run: |
          echo "Waiting for Minima to start..."
          while true; do
            response=$(curl -s -k https://127.0.0.1:9005/status 2>&1)
            echo "RPC status response: $response"
            if echo "$response" | grep -q "\"status\":true"; then
              break
            fi
            sleep 5
            echo "Still waiting for Minima..."
            docker logs minima9001 --tail 20
          done
          # Make a final RPC status call to verify and log the full response
          final_status=$(curl -s -k https://127.0.0.1:9005/status)
          echo "Final RPC status check: $final_status"
          echo "Minima is up and running!"
